### ISSUE TITLE
[Pre-2.7] Crash when hitting "O" in options

### ISSUE THREAD

**Issue by Sfven** [Sfven/finiteextreme#1]
Crashing when hitting "O for more options" in the options tab.

**Comment by Sfven** [comment]
`Description: Unexpected error`

`java.lang.NullPointerException: Unexpected error`
	`at net.eq2online.macros.core.MacroModCore.transformKeyBindings(MacroModCore.java:766)`
	`at net.eq2online.macros.core.MacroModCore.onRender(MacroModCore.java:735)`
	`at net.eq2online.macros.LiteModMacros.onRender(LiteModMacros.java:86)`
	`at com.mumfrey.liteloader.core.event.HandlerList$RenderListener5.onRender(HandlerList$RenderListener5.java:100)`
	`at com.mumfrey.liteloader.client.ClientEvents.onRender(ClientEvents.java:283)`
	`at com.mumfrey.liteloader.client.CallbackProxyClient.onRender(CallbackProxyClient.java:69)`
	`at com.mumfrey.liteloader.core.event.EventProxy.$event00004(EventProxy.java:215)`
	`at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1000)`
	`at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)`
	`at net.minecraft.client.main.Main.main(SourceFile:148)`
	`at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
	`at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)`
	`at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)`
	`at java.lang.reflect.Method.invoke(Unknown Source)`
	`at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)`
	`at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Seems to have to have something to do with the Macros mod. Will look into this.

**Comment by Sfven** [comment]
**Solution: Ended up removing Macros mod, fixed the issue.**
